### ISSUE TITLE
helm.kern 'eval' interface is not the CFIE

### ISSUE THREAD

**Issue by ahbarnett** [fastalgorithms/fmm3dbie#19]
I don't understand the point of the `eval` option to helm3d.kern  It seems to stack [aS, D] output matrices where a is the scale factor in varargin{1}.  But why not return aS+D as in CFIE?

**Comment by mrachh** [comment]
The 'eval' routine is meant for things like transmission problems, or even Neumann problems, where you have two different densities for the single and double layer potentials, as opposed to 'comb' or 'c' which is meant to be a combined field representation where S and D have the same density. It could use a better name, but since it arises both in transmission and Neumann problems, we didn't want to commit to either of those options.

**Comment by ahbarnett** [comment]
ok, got it.
